In [1]:
print("Hello World")

Hello World


In [7]:
def func1(x,y):
  if x>10:
    print("x greater than 10")
  elif y<10:
    print("y less than 10")
  else:
    print("ouside x and y")
  return x+y

func1(10,10)

ouside x and y


20

In [12]:
for i in range(5,25,5):
  print("running with i {}".format(i))
  r = func1(i,i)
  print(r)
  print("Result of func {} {}".format(str(i),str(r)))

running with i 5
y less than 10
10
Result of func 5 10
running with i 10
ouside x and y
20
Result of func 10 20
running with i 15
x greater than 10
30
Result of func 15 30
running with i 20
x greater than 10
40
Result of func 20 40


In [13]:
#loops
for i in range(2):
  print(i)
for i in [0,3]:
  print(i)

i =0
while i<5:
  print(i)
  i=i+1

0
1
0
3
0
1
2
3
4


In [14]:
#break
while True:
  print(True)
  break

True


In [16]:
#Numpy
import numpy as np
a = np.array(["Hello", "world"])
a = np.append(a,"!")
print("Current array {}".format(a))
for i in a:
  print(i)
for i,e in enumerate(a):
  print("{} {}".format(i,e))

Current array ['Hello' 'world' '!']
Hello
world
!
0 Hello
1 world
2 !


In [22]:
#math functions
b=np.array([1,2,3,4,5])
print(np.max(b))
print(np.average(b))
print(np.argmax(b))

5
3.0
4


In [23]:
print(type(b))

<class 'numpy.ndarray'>


In [19]:
c= np.random.rand(5,5)
print(c)

[[0.24342061 0.0040336  0.14522892 0.76570427 0.85987791]
 [0.65525074 0.28415554 0.12445048 0.96006291 0.4934457 ]
 [0.52330475 0.7847412  0.37602586 0.43643637 0.74674552]
 [0.89382889 0.94772707 0.4504244  0.22916639 0.74088353]
 [0.63250478 0.36008389 0.67948532 0.11665872 0.8608398 ]]


In [24]:
#shape
print(a.shape)
print(b.shape)
print(c.shape)

(3,)
(5,)
(5, 5)


COLAB SPECIFICS

In [2]:
!pwd
!cd /
!ls -l

/content
total 4
drwxr-xr-x 1 root root 4096 May 29 18:19 sample_data
